env:
  scenario: vm_scheduling
  topology: azure.2019.10k
  start_tick: 0
  durations: 8638
  resolution: 1
  seed: 777
  # start_tick: 1000

algorithm:
  # Random
  # type: random_pick.RandomPick
  # args:

  # FirstFit
  # type: first_fit.FirstFit
  # args:

  # BestFit
  type: best_fit.BestFit
  args:
    metric_type: "remaining_cpu_cores_and_energy_consumption"

  # Round Robin
  # type: round_robin.RoundRobin
  # args:

  # Bin packing
  # type: bin_packing.BinPacking
  # args:

  # DQN
  # type: dqn.DQNLauncher
  # args:

  # AC
  # type: ac.ACLauncher
  # args: